apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validator.webhooks.svc.cluster.local"
webhooks:
  - name: "validator.webhooks.svc.cluster.local"
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
        scope: "*"
    clientConfig:
      service:
        namespace: "webhook"
        name: "webhook-server"
        path: "/validate"
      caBundle: "CA_BUNDLE"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5